import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { readFile } from 'node:fs/promises'
import { CommitParser } from 'conventional-commits-parser'
import semver from 'semver'
const execute = promisify(execFile)
const header = /^([a-z][a-z0-9-]*)(?:\(([^()\r\n]+)\))?(!)?: (\S.*)$/
export const releaseFiles = ['package.json', 'package-lock.json', 'orca-plugin.json', 'CHANGELOG.md', 'README.md']
export async function git(cwd, args) {
  return (await execute('git', ['--no-pager', '-c', 'log.showSignature=false', ...args], { cwd, maxBuffer: 8 * 1024 * 1024 })).stdout.trimEnd()
}
export function parseCommit(message) {
  if (!header.test(message.split(/\r?\n/)[0])) throw Error(`Not a Conventional Commit: ${message.split(/\r?\n/)[0]}`)
  return new CommitParser({ headerPattern: header, headerCorrespondence: ['type', 'scope', 'breaking', 'subject'], noteKeywords: ['BREAKING CHANGE', 'BREAKING-CHANGE'] }).parse(message)
}
export function releaseType(commits) {
  let bump = null
  for (const { message } of commits) {
    const commit = parseCommit(message)
    if (commit.breaking || commit.notes.some((n) => /^BREAKING[ -]CHANGE$/i.test(n.title))) return 'major'
    if (commit.type === 'feat') bump = 'minor'
    else if (['fix', 'perf'].includes(commit.type) && !bump) bump = 'patch'
  }
  return bump
}
export function nextVersion(current, bump, prerelease) {
  if (!semver.valid(current) || !['major', 'minor', 'patch'].includes(bump)) throw Error('Invalid release version or type.')
  if (prerelease !== null && !/^[a-z][a-z0-9-]*$/.test(prerelease)) throw Error('Invalid prerelease channel.')
  const next = semver.inc(current, bump)
  if (!prerelease) return next
  if (semver.prerelease(current)?.[0] === prerelease && next === current.split('-')[0])
    return semver.inc(current, 'prerelease', prerelease)
  return `${next}-${prerelease}.1`
}
export async function readCommits(cwd, range = 'HEAD') {
  // Merge subjects generated by Git are skipped; their individual commits are checked.
  const raw = await git(cwd, ['log', '--no-merges', '--format=%H%x00%B%x00', range, '--'])
  const fields = raw.split('\0'), commits = []
  for (let i = 0; i + 1 < fields.length; i += 2) commits.push({ hash: fields[i].trim(), message: fields[i + 1].trimEnd() })
  return commits
}
export function releaseNotes(version, commits, prerelease) {
  return [`## v${version}`, '', ...(prerelease ? ['Preview release: stock-Orca Git URL installation, comment UI, real delivery and Windows desktop acceptance remain open. Automated release publication does not certify runtime acceptance.', ''] : []),
    ...commits.filter((c) => ['feat', 'fix', 'perf'].includes(parseCommit(c.message).type) || parseCommit(c.message).breaking || parseCommit(c.message).notes.length)
      .map((c) => `- ${c.message.split(/\r?\n/)[0]} (${c.hash.slice(0, 7)})`), ''].join('\n')
}
export async function prepareFiles(cwd, version, notes) {
  // Use node:path for native Windows paths rather than interpreting checkout text as a URL.
  const { join } = await import('node:path')
  const readJson = async (name) => JSON.parse(await readFile(join(cwd, name), 'utf8'))
  const pkg = await readJson('package.json'), lock = await readJson('package-lock.json'), manifest = await readJson('orca-plugin.json')
  pkg.version = manifest.version = lock.version = lock.packages[''].version = version
  const oldLog = await readFile(join(cwd, 'CHANGELOG.md'), 'utf8').catch((e) => { if (e.code === 'ENOENT') return '# Changelog\n\n'; throw e })
  const readme = await readFile(join(cwd, 'README.md'), 'utf8')
  const updatedReadme = readme.replace(/(https:\/\/github\.com\/Craig-Franklin\/orca-commit-review\.git#)v[0-9A-Za-z.+-]+/g, `$1v${version}`)
  if (updatedReadme === readme) throw Error('Could not update the pinned README installation URL.')
  return {
    'package.json': JSON.stringify(pkg, null, 2) + '\n',
    'package-lock.json': JSON.stringify(lock, null, 2) + '\n',
    'orca-plugin.json': JSON.stringify(manifest, null, 2) + '\n',
    'CHANGELOG.md': oldLog.replace(/^# Changelog\s*/, '# Changelog\n\n' + notes + '\n'),
    'README.md': updatedReadme
  }
}
export async function planRelease(cwd, config) {
  const { join } = await import('node:path')
  const head = await git(cwd, ['rev-parse', 'HEAD'])
  const pkg = JSON.parse(await readFile(join(cwd, 'package.json'), 'utf8'))
  const manifest = JSON.parse(await readFile(join(cwd, 'orca-plugin.json'), 'utf8'))
  if (pkg.version !== manifest.version) throw Error('Package and plugin versions disagree.')
  const tags = (await git(cwd, ['tag', '--merged', 'HEAD', '--list', 'v*'])).split('\n')
    .filter((t) => semver.valid(t.slice(1)) && (!semver.prerelease(t.slice(1)) || config.prerelease === null || semver.prerelease(t.slice(1))[0] === config.prerelease))
    .sort((a, b) => semver.rcompare(a.slice(1), b.slice(1)))
  let version = config.bootstrap.version, base = config.bootstrap.commit
  if (tags.length) { version = tags[0].slice(1); base = await git(cwd, ['rev-parse', `${tags[0]}^{commit}`]) }
  else {
    await git(cwd, ['merge-base', '--is-ancestor', base, head])
    const [baselineTree, publishedTree] = await Promise.all([git(cwd, ['rev-parse', `${base}^{tree}`]), git(cwd, ['rev-parse', `${config.bootstrap.tag}^{tree}`])])
    if (baselineTree !== publishedTree) throw Error('Rewritten bootstrap does not match the preserved preview tag.')
  }
  const commits = await readCommits(cwd, `${base}..${head}`)
  const headline = (await git(cwd, ['show', '-s', '--format=%s', head]))
  // Recovery after a signed release commit was accepted but tag/release publication failed.
  const releaseHeadline = `chore(release): v${pkg.version}`
  const pending = commits.find((c) => c.message.split('\n')[0] === releaseHeadline)
  if ((headline === releaseHeadline || (pending && pkg.version !== version)) && semver.gte(pkg.version, version)) {
    const releaseCommit = pending?.hash ?? head
    const changed = (await git(cwd, ['diff-tree', '--no-commit-id', '--name-only', '-r', releaseCommit])).split('\n')
    if (!changed.every((p) => releaseFiles.includes(p))) throw Error('Unexpected files in release recovery commit.')
    const source = await git(cwd, ['rev-parse', `${releaseCommit}^`])
    const body = await git(cwd, ['show', '-s', '--format=%B', releaseCommit])
    if (!body.includes(`Release-Source: ${source}`)) throw Error('Release recovery source is missing.')
    const releaseBase = /^Release-Base: ([a-f0-9]{40})$/m.exec(body)?.[1]
    if (!releaseBase) throw Error('Release recovery base is missing.')
    await git(cwd, ['merge-base', '--is-ancestor', releaseBase, source])
    return { head, releaseCommit, version: pkg.version, tag: `v${pkg.version}`, recovery: true, pending: pkg.version !== version,
      notes: releaseNotes(pkg.version, await readCommits(cwd, `${releaseBase}..${source}`), config.prerelease) }
  }
  if (pkg.version !== version) throw Error('Manifest version differs from the latest release. Recover the pending release before adding new changes.')
  const bump = releaseType(commits)
  if (!bump) return { head, skip: true, reason: 'No feature, fix, performance or breaking commits since the last release.' }
  const next = nextVersion(version, bump, config.prerelease)
  const notes = releaseNotes(next, commits, config.prerelease)
  return { head, base, bump, version: next, tag: `v${next}`, notes, files: await prepareFiles(cwd, next, notes) }
}
